spring:
  application:
    name: Produtos API
  datasource:
    url: jdbc:h2:mem:produtos
    username: sa
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # para criar/update tabelas automaticamente
  h2:
    console:
      enabled: true
      path: /h2-console